//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zyronator
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscogsUserList
    {
        public int ListId { get; set; }
        public int DiscogsId { get; set; }
        public string ListName { get; set; }
        public string ResourceUrl { get; set; }
        public string Uri { get; set; }
        public string ListDescription { get; set; }
    }
}
